version: '3'
services:
  db:
    container_name: settle-db
    image: mariadb:jammy
    volumes:
      - maria:/var/lib/mysql
    environment:
      - MARIADB_USER=maria-user
      - MARIADB_PASSWORD=maria-pass
      - MARIADB_ROOT_PASSWORD=root-user-password`
      - MARIADB_DATABASE=settle-db
    networks:
      - maria_network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.0-apache
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - maria_network

  nginx-settle:
    depends_on:
      - db
    container_name: nginx-settle
    ports:
      - "8080:80"
    image: tuahil/settle-alpine
    networks:
      - nginx_network
      - maria_network

volumes:
  maria:

networks:
  maria_network:
    driver: bridge
  nginx_network:
    driver: bridge
  
    





